## Phishing Site Detection

In the Pre processing of the Data the attributes are coded into following format for application of KNN Classifier 

 	SFH's type is nominal, range is ('1', '-1', '0')
 	popUpWidnow's type is nominal, range is ('-1', '0', '1')
 	SSLfinal_State's type is nominal, range is ('1', '-1', '0')
 	Request_URL's type is nominal, range is ('-1', '0', '1')
 	URL_of_Anchor's type is nominal, range is ('-1', '0', '1')
 	web_traffic's type is nominal, range is ('1', '0', '-1')
 	URL_Length's type is nominal, range is ('1', '-1', '0')
 	age_of_domain's type is nominal, range is ('1', '-1')
 	having_IP_Address's type is nominal, range is ('0', '1')
 	Result's type is nominal, range is ('0', '1', '-1'))
    
    The  data coding is as follows:
    "1"  - Legitimate Website
    "0"  - Suspisious
    "-1" - Malicious Website

### Importing the packages

ARFF stands for Attribute-Relation File Format. To read this file we will import package loadarff.


In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from scipy.io.arff import loadarff
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

### Loading the data

In [2]:
phishing_data_raw = loadarff("attachment_PhishingData_lyst6650.arff")

In [3]:
phishing_data_raw

(array([(b'-1', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'-1', b'-1', b'1', b'1', b'-1', b'1', b'-1', b'1', b'-1', b'-1', b'-1', b'0', b'1', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'-1', b'1', b'1', b'-1', b'-1'),
        (b'1', b'1', b'1', b'1', b'1', b'-1', b'0', b'1', b'-1', b'1', b'1', b'-1', b'1', b'0', b'-1', b'-1', b'1', b'1', b'0', b'1', b'1', b'1', b'1', b'-1', b'-1', b'0', b'-1', b'1', b'1', b'1', b'-1'),
        (b'1', b'0', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'-1', b'1', b'1', b'-1', b'1', b'0', b'-1', b'-1', b'-1', b'-1', b'0', b'1', b'1', b'1', b'1', b'1', b'-1', b'1', b'-1', b'1', b'0', b'-1', b'-1'),
        ...,
        (b'1', b'-1', b'1', b'1', b'1', b'-1', b'1', b'-1', b'-1', b'1', b'1', b'1', b'1', b'0', b'-1', b'-1', b'1', b'1', b'0', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'-1', b'1', b'0', b'1', b'-1'),
        (b'-1', b'-1', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'1', b'-1', b'1', b'1', b'-1', b'-1', b'1', b'-1', b'1', b'1', b'0', b'-1', b'1', b'-1', b'1'

In [4]:
len(phishing_data_raw)

2

In [5]:
# Selection of the Data and converting data into numpy format for flexibility in cleaning
phising_data_array = np.array(phishing_data_raw[0])
phising_data_array

array([(b'-1', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'-1', b'-1', b'1', b'1', b'-1', b'1', b'-1', b'1', b'-1', b'-1', b'-1', b'0', b'1', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'-1', b'1', b'1', b'-1', b'-1'),
       (b'1', b'1', b'1', b'1', b'1', b'-1', b'0', b'1', b'-1', b'1', b'1', b'-1', b'1', b'0', b'-1', b'-1', b'1', b'1', b'0', b'1', b'1', b'1', b'1', b'-1', b'-1', b'0', b'-1', b'1', b'1', b'1', b'-1'),
       (b'1', b'0', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'-1', b'1', b'1', b'-1', b'1', b'0', b'-1', b'-1', b'-1', b'-1', b'0', b'1', b'1', b'1', b'1', b'1', b'-1', b'1', b'-1', b'1', b'0', b'-1', b'-1'),
       ...,
       (b'1', b'-1', b'1', b'1', b'1', b'-1', b'1', b'-1', b'-1', b'1', b'1', b'1', b'1', b'0', b'-1', b'-1', b'1', b'1', b'0', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'-1', b'1', b'0', b'1', b'-1'),
       (b'-1', b'-1', b'1', b'1', b'1', b'-1', b'-1', b'-1', b'1', b'-1', b'1', b'1', b'-1', b'-1', b'1', b'-1', b'1', b'1', b'0', b'-1', b'1', b'-1', b'1', b'1'

In [6]:
phising_data_array.shape

(11055,)

In [7]:
# Converting the numpy array into Pandas data frame  and casting the columns to numeric type
phising_data_frame = pd.DataFrame(phising_data_array).apply(pd.to_numeric)
phising_data_frame.head()

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon   ...    popUpWidnow  Iframe  \
0                           -1        1   ...              1       1   
1                           -1        1   ...              1       1   
2                           -1        1   ...              1       1   
3                            1        1   ...              1       1   
4                           -1        1   ...             -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1      -1  
1                       1                   1      -1  
2                       0                  -1      -1  
3                      -1                   1      -1  
4                       1                   1       1  

[5 rows x 31 columns]

In [8]:
phising_data_frame.describe().T

count      mean       std  min  25%  50%  75%  \
having_IP_Address            11055.0  0.313795  0.949534 -1.0 -1.0  1.0  1.0   
URL_Length                   11055.0 -0.633198  0.766095 -1.0 -1.0 -1.0 -1.0   
Shortining_Service           11055.0  0.738761  0.673998 -1.0  1.0  1.0  1.0   
having_At_Symbol             11055.0  0.700588  0.713598 -1.0  1.0  1.0  1.0   
double_slash_redirecting     11055.0  0.741474  0.671011 -1.0  1.0  1.0  1.0   
Prefix_Suffix                11055.0 -0.734962  0.678139 -1.0 -1.0 -1.0 -1.0   
having_Sub_Domain            11055.0  0.063953  0.817518 -1.0 -1.0  0.0  1.0   
SSLfinal_State               11055.0  0.250927  0.911892 -1.0 -1.0  1.0  1.0   
Domain_registeration_length  11055.0 -0.336771  0.941629 -1.0 -1.0 -1.0  1.0   
Favicon                      11055.0  0.628584  0.777777 -1.0  1.0  1.0  1.0   
port                         11055.0  0.728268  0.685324 -1.0  1.0  1.0  1.0   
HTTPS_token                  11055.0  0.675079  0.737779 -1.0  1.0  1.0  1.0   
Request_URL                  11055.0  0.186793  0.982444 -1.0 -1.0  1.0  1.0   
URL_of_Anchor                11055.0 -0.076526  0.715138 -1.0 -1.0  0.0  0.0   
Links_in_tags                11055.0 -0.118137  0.763973 -1.0 -1.0  0.0  0.0   
SFH                          11055.0 -0.595749  0.759143 -1.0 -1.0 -1.0 -1.0   
Submitting_to_email          11055.0  0.635640  0.772021 -1.0  1.0  1.0  1.0   
Abnormal_URL                 11055.0  0.705292  0.708949 -1.0  1.0  1.0  1.0   
Redirect                     11055.0  0.115694  0.319872  0.0  0.0  0.0  0.0   
on_mouseover                 11055.0  0.762099  0.647490 -1.0  1.0  1.0  1.0   
RightClick                   11055.0  0.913885  0.405991 -1.0  1.0  1.0  1.0   
popUpWidnow                  11055.0  0.613388  0.789818 -1.0  1.0  1.0  1.0   
Iframe                       11055.0  0.816915  0.576784 -1.0  1.0  1.0  1.0   
age_of_domain                11055.0  0.061239  0.998168 -1.0 -1.0  1.0  1.0   
DNSRecord                    11055.0  0.377114  0.926209 -1.0 -1.0  1.0  1.0   
web_traffic                  11055.0  0.287291  0.827733 -1.0  0.0  1.0  1.0   
Page_Rank                    11055.0 -0.483673  0.875289 -1.0 -1.0 -1.0  1.0   
Google_Index                 11055.0  0.721574  0.692369 -1.0  1.0  1.0  1.0   
Links_pointing_to_page       11055.0  0.344007  0.569944 -1.0  0.0  0.0  1.0   
Statistical_report           11055.0  0.719584  0.694437 -1.0  1.0  1.0  1.0   
Result                       11055.0  0.113885  0.993539 -1.0 -1.0  1.0  1.0   

                             max  
having_IP_Address            1.0  
URL_Length                   1.0  
Shortining_Service           1.0  
having_At_Symbol             1.0  
double_slash_redirecting     1.0  
Prefix_Suffix                1.0  
having_Sub_Domain            1.0  
SSLfinal_State               1.0  
Domain_registeration_length  1.0  
Favicon                      1.0  
port                         1.0  
HTTPS_token                  1.0  
Request_URL                  1.0  
URL_of_Anchor                1.0  
Links_in_tags                1.0  
SFH                          1.0  
Submitting_to_email          1.0  
Abnormal_URL                 1.0  
Redirect                     1.0  
on_mouseover                 1.0  
RightClick                   1.0  
popUpWidnow                  1.0  
Iframe                       1.0  
age_of_domain                1.0  
DNSRecord                    1.0  
web_traffic                  1.0  
Page_Rank                    1.0  
Google_Index                 1.0  
Links_pointing_to_page       1.0  
Statistical_report           1.0  
Result                       1.0

In [9]:
phising_data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 31 columns):
having_IP_Address              11055 non-null int64
URL_Length                     11055 non-null int64
Shortining_Service             11055 non-null int64
having_At_Symbol               11055 non-null int64
double_slash_redirecting       11055 non-null int64
Prefix_Suffix                  11055 non-null int64
having_Sub_Domain              11055 non-null int64
SSLfinal_State                 11055 non-null int64
Domain_registeration_length    11055 non-null int64
Favicon                        11055 non-null int64
port                           11055 non-null int64
HTTPS_token                    11055 non-null int64
Request_URL                    11055 non-null int64
URL_of_Anchor                  11055 non-null int64
Links_in_tags                  11055 non-null int64
SFH                            11055 non-null int64
Submitting_to_email            11055 non-null int64
Abnorma

**Observation**: There are no missing values in the dataset. 

In [10]:
phising_data_frame['Result'].value_counts()           # Checking the number of target labels

 1    6157
-1    4898
Name: Result, dtype: int64

**Observation**: This is classification problem so check for balance. The dataset is more or less balanced.

In [11]:
phising_data_frame.columns                            # Lets check all the columns of the dataframe

Index(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')

In [12]:
# Extracting Result column to pass as target label

Y = phising_data_frame["Result"].values
print(Y)

[-1 -1 -1 ... -1 -1 -1]


In [13]:
col_names = list(phising_data_frame)


In [14]:
predictor_cols = col_names[0:len(col_names)-2]                 # selecting the predictor column names

# Extracting Input Features to build the model 

X = phising_data_frame[predictor_cols].values
X

array([[-1,  1,  1, ..., -1,  1,  1],
       [ 1,  1,  1, ..., -1,  1,  1],
       [ 1,  0,  1, ..., -1,  1,  0],
       ...,
       [ 1, -1,  1, ..., -1,  1,  0],
       [-1, -1,  1, ..., -1,  1,  1],
       [-1, -1,  1, ..., -1, -1,  1]], dtype=int64)

### Model Fitting

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=101)

In [16]:
clf_knn = KNeighborsClassifier(
    n_neighbors=10,
    weights='distance'
    )
clf_knn = clf_knn.fit(X_train,y_train)

In [17]:
score_knn = cross_val_score(clf_knn, X, Y, cv=5)
print("Cross Validation score with 5 folds: " + str(score_knn))
print("Cross Validation Mean score : " + str(score_knn.mean()))

Cross Validation score with 5 folds: [0.98101266 0.97377939 0.96291271 0.93846154 0.92171946]
Cross Validation Mean score : 0.9555771496112235


In [18]:
score_knn = cross_val_score(clf_knn, X, Y, cv=10)
print("Cross Validation score with 10 folds: " + str(score_knn))
print("Cross Validation Mean score : " + str(score_knn.mean()))

Cross Validation score with 10 folds: [0.98462929 0.98191682 0.96383363 0.98643761 0.9755877  0.960217
 0.93761302 0.93484163 0.94112319 0.95561594]
Cross Validation Mean score : 0.9621815840768381


In [23]:
clf_knn.classes_, clf_knn.effective_metric_, clf_knn.effective_metric_params_ 

(array([-1,  1], dtype=int64), 'euclidean', {})

In [20]:
y_pred = clf_knn.predict(X_test)

In [21]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

          -1       0.94      0.95      0.94       971
           1       0.96      0.95      0.96      1240

   micro avg       0.95      0.95      0.95      2211
   macro avg       0.95      0.95      0.95      2211
weighted avg       0.95      0.95      0.95      2211



In [22]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 919   52]
 [  56 1184]]


In [23]:
print(accuracy_score(y_test, y_pred))

0.9511533242876526


### Grid Search

In [34]:
from sklearn.model_selection import GridSearchCV

grid_params = {'n_neighbors': [5,7,9,11,13,15]}

gs = GridSearchCV(clf_knn, 
                 grid_params,
                 verbose=1,
                 cv=5,
                 n_jobs=-1)

gs_result = gs.fit(X_train, y_train)
y_pred = gs_result.predict(X_test)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:  1.1min finished


In [32]:
gs.best_params_, gs.best_score_, gs.n_splits_

({'n_neighbors': 7}, 0.9549977385798282, 5)

In [35]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

          -1       0.95      0.95      0.95       971
           1       0.96      0.96      0.96      1240

   micro avg       0.95      0.95      0.95      2211
   macro avg       0.95      0.95      0.95      2211
weighted avg       0.95      0.95      0.95      2211



In [36]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 922   49]
 [  51 1189]]


In [37]:
print(accuracy_score(y_test, y_pred))

0.9547715965626413
